<a href="https://colab.research.google.com/github/Salim-Muhammed/Excel_Dashboard/blob/main/credit_score_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Credit Score Classification Dataset.csv")
df

Age  Gender  Income            Education Marital Status  \
0     25  Female   50000    Bachelor's Degree         Single   
1     30    Male  100000      Master's Degree        Married   
2     35  Female   75000            Doctorate        Married   
3     40    Male  125000  High School Diploma         Single   
4     45  Female  100000    Bachelor's Degree        Married   
..   ...     ...     ...                  ...            ...   
159   29  Female   27500  High School Diploma         Single   
160   34    Male   47500   Associate's Degree         Single   
161   39  Female   62500    Bachelor's Degree        Married   
162   44    Male   87500      Master's Degree         Single   
163   49  Female   77500            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [5]:
df.head()

Age  Gender  Income            Education Marital Status  \
0   25  Female   50000    Bachelor's Degree         Single   
1   30    Male  100000      Master's Degree        Married   
2   35  Female   75000            Doctorate        Married   
3   40    Male  125000  High School Diploma         Single   
4   45  Female  100000    Bachelor's Degree        Married   

   Number of Children Home Ownership Credit Score  
0                   0         Rented         High  
1                   2          Owned         High  
2                   1          Owned         High  
3                   0          Owned         High  
4                   3          Owned         High

In [6]:
df.tail()

Age  Gender  Income            Education Marital Status  \
159   29  Female   27500  High School Diploma         Single   
160   34    Male   47500   Associate's Degree         Single   
161   39  Female   62500    Bachelor's Degree        Married   
162   44    Male   87500      Master's Degree         Single   
163   49  Female   77500            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Age                 164 non-null    int64 
 1   Gender              164 non-null    object
 2   Income              164 non-null    int64 
 3   Education           164 non-null    object
 4   Marital Status      164 non-null    object
 5   Number of Children  164 non-null    int64 
 6   Home Ownership      164 non-null    object
 7   Credit Score        164 non-null    object
dtypes: int64(3), object(5)
memory usage: 10.4+ KB


In [8]:
df.isna().sum()

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [9]:
df.describe().T

count          mean           std      min       25%  \
Age                 164.0     37.975610      8.477289     25.0     30.75   
Income              164.0  83765.243902  32457.306728  25000.0  57500.00   
Number of Children  164.0      0.652439      0.883346      0.0      0.00   

                        50%       75%       max  
Age                    37.0      45.0      53.0  
Income              83750.0  105000.0  162500.0  
Number of Children      0.0       1.0       3.0

In [10]:
df.drop(['Gender'],axis=1,inplace=True)
df

Age  Income            Education Marital Status  Number of Children  \
0     25   50000    Bachelor's Degree         Single                   0   
1     30  100000      Master's Degree        Married                   2   
2     35   75000            Doctorate        Married                   1   
3     40  125000  High School Diploma         Single                   0   
4     45  100000    Bachelor's Degree        Married                   3   
..   ...     ...                  ...            ...                 ...   
159   29   27500  High School Diploma         Single                   0   
160   34   47500   Associate's Degree         Single                   0   
161   39   62500    Bachelor's Degree        Married                   2   
162   44   87500      Master's Degree         Single                   0   
163   49   77500            Doctorate        Married                   1   

    Home Ownership Credit Score  
0           Rented         High  
1            Owned         High  
2            Owned         High  
3            Owned         High  
4            Owned         High  
..             ...          ...  
159         Rented          Low  
160         Rented      Average  
161          Owned         High  
162          Owned         High  
163          Owned         High  

[164 rows x 7 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Education'] = le.fit_transform(df['Education'])
df['Marital Status'] = le.fit_transform(df['Marital Status'])
df['Home Ownership'] = le.fit_transform(df['Home Ownership'])
df


Age  Income  Education  Marital Status  Number of Children  \
0     25   50000          1               1                   0   
1     30  100000          4               0                   2   
2     35   75000          2               0                   1   
3     40  125000          3               1                   0   
4     45  100000          1               0                   3   
..   ...     ...        ...             ...                 ...   
159   29   27500          3               1                   0   
160   34   47500          0               1                   0   
161   39   62500          1               0                   2   
162   44   87500          4               1                   0   
163   49   77500          2               0                   1   

     Home Ownership Credit Score  
0                 1         High  
1                 0         High  
2                 0         High  
3                 0         High  
4                 0         High  
..              ...          ...  
159               1          Low  
160               1      Average  
161               0         High  
162               0         High  
163               0         High  

[164 rows x 7 columns]

In [14]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)

In [18]:
from pandas.core.indexes import base
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
model=SVC()
lst_model=[knn,base,model]


In [19]:
for i in lst_model:
  print(i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("---------------------------------------------------------------")
  print(accuracy_score(y_test,y_pred))
  print("---------------------------------------------------------------")
  print(confusion_matrix(y_test,y_pred))
  print("---------------------------------------------------------------")
  print(classification_report(y_test,y_pred))


KNeighborsClassifier(n_neighbors=7)
---------------------------------------------------------------
0.9
---------------------------------------------------------------
[[ 9  2  0]
 [ 1 31  0]
 [ 2  0  5]]
---------------------------------------------------------------
              precision    recall  f1-score   support

     Average       0.75      0.82      0.78        11
        High       0.94      0.97      0.95        32
         Low       1.00      0.71      0.83         7

    accuracy                           0.90        50
   macro avg       0.90      0.83      0.86        50
weighted avg       0.91      0.90      0.90        50

GaussianNB()
---------------------------------------------------------------
0.94
---------------------------------------------------------------
[[ 9  2  0]
 [ 1 31  0]
 [ 0  0  7]]
---------------------------------------------------------------
              precision    recall  f1-score   support

     Average       0.90      0.82      0.86     